Enhance the v1 script

diff --git a/scripts/v1 b/scripts/v1
--- a/scripts/v1
+++ b/scripts/v1
@@ -4,4 +4,15 @@ echo "Compiling v1:"
 ./src/bootstrap/v0/v0fromv0.exe < src/bootstrap/v1/v1.d > v1.asm && nasm -fwin64 v1.asm && gcc v1.obj -o v1.exe || exit
 # compile target with v1
 echo "Compiling target:"
-./v1.exe < $PWD/$1| tee temp.asm && nasm -fwin64 temp.asm && gcc temp.obj -o temp.exe && ./temp.exe
+./v1.exe < $PWD/$1 > temp.asm 
+if [ $? -ne 0 ] 
+then
+  echo "Compilation error"
+  cat temp.asm
+  exit -1
+fi
+
+nasm -fwin64 temp.asm && gcc temp.obj -o temp.exe || exit
+echo "Running target:"
+echo "==============="
+./temp.exe
